# .circleci/config.yml
version: 2

dependencies:
  pre:
    - gem install bundler

jobs:
  build-ios:
    macos:
      xcode: '11.2.1'
    steps:
      - checkout
      - run: echo "ruby-2.4.5" > ~/.ruby-version
      - run: npm -g install ionic@5
      - run: npm install
      - run: sudo gem install bundler
      - run: bundle install
      - run: bundle exec pod setup
      - run: bundle exec fastlane ios staging --env dev
  build-android:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install gradle
      - run: mkdir "./.android_signing"
      - run: echo "$ANDROID_KEYSTORE_DATA" | base64 -d > "./.android_signing/smartfin.keystore"
      - run: sudo npm -g install ionic@5
      - run: npm install
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec fastlane android staging --env dev

workflows:
  version: 2
  build:
    jobs:
      - build-ios
      - build-android
